AllCops:
  TargetRubyVersion: 2.3

# These linters are not enabled by default
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# These help with readability
Layout/CaseIndentation:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  Exclude:
    - 'testing/rspec/spec/**/*' # Specs tend to just have little monkey patches that don't need the extra room
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/LineLength:
  Max: 120
Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength:
  Exclude:
    - 'testing/rspec/spec/**/*' # RSpec tests are inherently large blocks of code
    - 'cuke_modeler.gemspec' # As is a gemspec
    - 'Rakefile' # And a Rakefile

# Just not going to worry about it for now
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: 'implicit'
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

# Still within understanding as long as other complexity cops aren't triggering
Metrics/MethodLength:
  Max: 15

# I'd rather not have to mix `{}` and `do...end` blocks for `let` statements just to keep RuboCop happy
Layout/BlockEndNewline:
  Exclude:
    - 'testing/rspec/spec/**/*'
Layout/MultilineBlockLayout:
  Exclude:
    - 'testing/rspec/spec/**/*'
Style/BlockDelimiters:
  Exclude:
    - 'testing/rspec/spec/**/*'

# Documentation is checked using RDoc
Style/Documentation:
  Enabled: false

Security/Eval:
  Exclude:
    - 'testing/**/*'  # Test code is a safe enough place to use 'eval'
