inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

# These linters are not enabled by default
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# These help with readability
Layout/CaseIndentation:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength:
  Exclude:
    - 'testing/rspec/spec/**/*' # RSpec tests are inherently large blocks of code
    - 'cuke_modeler.gemspec' # As is a gemspec
    - 'Rakefile' # And a Rakefile

# Just not going to worry about it for now
Style/FrozenStringLiteralComment:
  Enabled: false

# Still within understanding as long as other complexity cops aren't triggering
Metrics/MethodLength:
  Max: 15
