inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

# These linters are not enabled by default
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# These help with readability
Layout/CaseIndentation:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case

# RSpec tests are inherently large blocks of code
Metrics/BlockLength:
  Exclude:
    - 'testing/rspec/spec/**/*'
