os:
  - linux
  - osx

# JRuby isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.1.7.0

gemfile:
  - testing/gemfiles/gherkin9.gemfile
  - testing/gemfiles/gherkin10.gemfile
  - testing/gemfiles/gherkin11.gemfile
  - testing/gemfiles/gherkin12.gemfile
  - testing/gemfiles/gherkin13.gemfile

matrix:
  exclude:

    # Ruby 2.3.x is currently broken on TravisCI for OSX and is no longer a supported Ruby version, anyway.
    - rvm: 2.3.8
      os: osx

before_install:
  - gem install bundler -v '< 2'

script: bundle exec rake cuke_modeler:ci_build
