name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['2.3', '2.5', '2.7', '3.0', 'jruby-9.1.17.0']
        gemfile: [ gherkin9, gherkin10, gherkin12, gherkin13, gherkin14,
                   gherkin15, gherkin16, gherkin17, gherkin18, gherkin19 ]
    runs-on: ${{ matrix.os }}
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: testing/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI Rake task
        run: bundle exec rake cuke_modeler:ci_build
